Make no-underscore-dangle specific
meteor/eslint-config-meteor pull request #2
Opened 2017-03-31 23:35 UTC by merlinpatt

Instead of turning off no-underscore-dangle, it would be better to allow specific Meteor things that have it.

In my projects, I've only ever used `_id`, and `_ensureIndex`. I'm not sure if there are others.

2017-04-04 04:19 UTC, abernix requested changes
Looks reasonable.  Could you pretty-print this across multiple lines?

2017-04-04 15:26 UTC, abernix approved these changes

2017-04-04 23:49 UTC, dburles commented
I think this is okay, however the only downside here is that Meteor internals rely heavily on this convention and on some occasions you'll reach in to make use of them. One example of that is when writing your own accounts package.

2017-04-04 23:51 UTC, merged

2017-04-04 23:52 UTC, dburles reviewed
lgtm!

2017-04-05 07:35 UTC, abernix commented
Published as `@meteorjs/eslint-config-meteor@1.0.3`!

2017-04-05 07:37 UTC, abernix commented
![image](https://cloud.githubusercontent.com/assets/841294/24694742/c48210ba-19eb-11e7-9615-70612fe5121e.png)

This might not be too hard since `eslint` is, in a way, a test-runner for this package.